import type { Metadata } from 'next';
import { Single_Day } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const inter = Single_Day({ subsets: ['latin'], variable: '--font-single-day' });

const proggy = localFont({
  src: './fonts/proggycleantt.ttf',
  display: 'swap',
  variable: '--font-progy',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${proggy.variable}`}>{children}</body>
    </html>
  );
}
