import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const manrope = Manrope({ subsets: ['latin'], variable: '--font-manrope' });

const proggy = localFont({
  src: './fonts/proggycleantt.ttf',
  display: 'swap',
  variable: '--font-proggy',
});

export const metadata: Metadata = {
  title: 'David Onifade Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${proggy.variable}`}>{children}</body>
    </html>
  );
}
